// AUTO-GENERATED by ink-ui-explorer M5 repair pipeline (M6.T1 simulated run).
//
// Source dump: test/fixtures/explorer-dumps/regression-bug-a.md
// Source fixture: /data/xtzhang/Nuka/test/ui-auto/fixtures/regression-bug-a.fixtures.tsx
// Root cause: prompt surface had no "When NOT to use" guidance for TodoWrite
// First violation: prompt-surface-missing-when-not-to-use
// Failing viewport: 120x30
//
// This fixture mounts the same case the original dump observed at the
// same viewport. Any regression of the bug re-fires the invariant.

import original from '../regression-bug-a.fixtures'
import type { FixtureDef } from '../../../../src/core/testing/explorer/types'

const sourceCase = original.cases["tool-description-has-when-not-to-use"]
if (!sourceCase) {
  throw new Error(
    'regression-bug-a-001: case tool-description-has-when-not-to-use missing from original fixture',
  )
}

const fixture: FixtureDef = {
  component: "BugA-TodoWritePromptSurface",
  cases: {
    ["regression_bug-a-001"]: sourceCase,
  },
  viewports: [{ cols: 120, rows: 30 }],
}

export default fixture
